-- supabase-init.sql
-- Run this in Supabase Dashboard -> SQL Editor

-- 1) Create the example table
CREATE TABLE IF NOT EXISTS public.signups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- 2) Ensure row level security is enabled (Supabase projects often have RLS on)
ALTER TABLE public.signups ENABLE ROW LEVEL SECURITY;

-- 3) Demo policies: allow anonymous client to INSERT and SELECT (NOT for production)
-- These policies are intentionally permissive so client-side anon key can read/write for a quick demo.

-- Ensure policies are created. CREATE POLICY does not support IF NOT EXISTS in Postgres,
-- so DROP any existing policy first, then CREATE it.
DROP POLICY IF EXISTS "Allow public select" ON public.signups;
CREATE POLICY "Allow public select" ON public.signups
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Allow public insert" ON public.signups;
CREATE POLICY "Allow public insert" ON public.signups
  FOR INSERT
  WITH CHECK (true);

-- IMPORTANT NOTES
-- - For production, do NOT use permissive policies. Limit access to authenticated users:
--     CREATE POLICY "Allow authenticated insert" ON public.signups
--       FOR INSERT
--       WITH CHECK (auth.role() = 'authenticated');
--     CREATE POLICY "Allow authenticated select" ON public.signups
--       FOR SELECT
--       USING (auth.role() = 'authenticated');
-- - Alternatively, keep the keys server-side and use a service role key from a trusted backend.

-- Troubleshooting "Could not find the table 'public.signups' in the schema cache":
-- 1) Confirm this SQL runs successfully in Supabase SQL Editor and the table appears in Table Editor → public → signups.
-- 2) If you added the table while an Edge Function, Realtime listener, or server process was running, redeploy/restart that function/process so the schema cache refreshes.
-- 3) Wait ~30s and retry; Supabase sometimes needs a short time to update internal caches.
-- 4) If the error persists and you use serverless functions (Vercel), redeploy the Vercel deployment or restart the dev server.

-- End of file

-- Optional: create `contacts` table (used by the frontend form)
CREATE TABLE IF NOT EXISTS public.contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public select" ON public.contacts;
CREATE POLICY "Allow public select" ON public.contacts
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Allow public insert" ON public.contacts;
CREATE POLICY "Allow public insert" ON public.contacts
  FOR INSERT
  WITH CHECK (true);
